name: Sync Past Submissions

on:
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: joshpan/codeforces-sync-action@master
        with:
          handle: taraqaziz508
